cookie:
  expiry_days: 30
  key: some_signature_key # Must be a string
  name: some_cookie_name

credentials:
  usernames:
    wochoka:
      email: wochoka@altaiconsulting.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Wesley
      last_name: Choka
      logged_in: False # Will be managed automatically
      password: G5$7kLz!8W # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer
    ekinuthia:
      email: ekinuthia@altaiconsulting.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Elijah
      last_name: Kinuthia
      logged_in: False # Will be managed automatically
      password: G5$7kLz!8W # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer
    mmshindi:
      email: mmshindi@altaiconsulting.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Milton
      last_name: Mshindi
      logged_in: False # Will be managed automatically
      password: Z9@qK2#bLm # Will be hashed automatically
      roles: # Optional
      - admin
      - viewer

    reastwood:
      email: reastwood@altaiconsulting.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Rose
      last_name: Eastwood
      logged_in: False # Will be managed automatically
      password: Z9@qK2#bLm # Will be hashed automatically
      roles: # Optional
      - admin
      - viewer

    sali:
      email: sali@altaiconsulting.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Saadia
      last_name: Ali
      logged_in: False # Will be managed automatically
      password: Z9@qK2#bLm # Will be hashed automatically
      roles: # Optional
      - admin
      - viewer

    dshah:
      email: dshah@altaiconsulting.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Dhvani
      last_name: Sha
      logged_in: False # Will be managed automatically
      password: Z9@qK2#bLm # Will be hashed automatically
      roles: # Optional
      - admin
      - viewer

    fs:
      email:
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Field
      last_name: Supervisor
      logged_in: False # Will be managed automatically
      password: H8!rB2%vQp # Will be hashed automatically
      roles: # Optional
      - viewer

    ftl:
      email:
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Team
      last_name: Leader
      logged_in: False # Will be managed automatically
      password: J3@wX6#dPq # Will be hashed automatically
      roles: # Optional
      - viewer